### ISSUE TITLE
Python reverse operators (like __radd__) are not working with 'swig -builtin'

### ISSUE THREAD

**Issue by srohit0** [ai-techsystems/dnnCompiler#34]
## Description
Python allows to overload operators in normal and reverse fashion. 

Given, ```x=dc.arange(5)```, ```y=x+1``` calls dnnc tensor **operator+**  (aka \_\_add__ operator), whereas ```y=1+x``` calls dnnc tensor **reverse operator +**  (aka \_\_radd__ operator).

If you compile with ```swig -builtin``` _OR_ ```make FAST_SWIG=n``` for performance reasons, reverse operators stop working.

## How to Reproduce
*Script: bug.py*
```
import dnnc as dc

x=dc.arange(4)
y=x+1;              # works
y=1+x;              # fails with swig -builtin
print("PASS :-)")
```
---
> % make clean; make
> % python bug.py
```
Traceback (most recent call last):
  File "bug.py", line 5, in <module>
    y=1+x; #fails with swig -builtin
TypeError: unsupported operand type(s) for +: 'int' and 'dnnc.fTensor'
```
---
> % make clean ; make FAST_SWIG=n
> % python bug.py
```
PASS :-)
```

**Comment by Gunjan933** [comment]
Swig doesn't support `__radd__` if you are using *-bulitin*

**Comment by Gunjan933** [comment]
## Closing this as the solution is described in the previous comment.
