### ISSUE TITLE
NN operators don't work on scalars

### ISSUE THREAD

**Issue by srohit0** [ai-techsystems/dnnCompiler#89]
NN operators like ```dc.sqrt(5.0)``` don't work, because swig does not **implicitly convert** python scalars like float to tensor<float>. It works fine in C++.

Symptom of this is that ```dc.sqrt()``` works on tensor, not on scalars as shown in the script below

```
import deepC.dnnc as dc
a=dc.arange(5)
dc.sqrt(a); #<<<<<<<< works on tensor 
[0.000000 1.000000 1.414214 1.732051 2.000000]
dc.sqrt(a.sum()) ; # <<<<<<<<<< throws on scalar
```

> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/home/amd/dnnc/master/dnnCompiler/deepC/dnnc.py", line 16108, in sqrt
>    return _dnnc.sqrt(*args)
> NotImplementedError: Wrong number or type of arguments for overloaded function 'sqrt'.
>  Possible C/C++ prototypes are:
>    dnnc::sqrt(dnnc::tensor< float > &)
>    dnnc::sqrt(dnnc::tensor< double > &)

## Solution Hint
Make swig work on ```%imlicitconv dnnc::tensor;``` for tensor class.

**Comment by Gunjan933** [comment]
Added in 69485a69cf7237f1eee828ebcc013002985a0dfb
